<h2>Liste des medias</h2>

<table border="1px">
	<tr>
		<th>ID Media</th>
		<th>Nom</th>
		<th>URL</th>
	</tr>

	<?php $medias = $block->afficher(); ?>
	<?php foreach ($medias as $item) :?>
	<tr>
		<td><?php echo $item['id']; ?></td>
		<td><?php echo $item['name']; ?></td>
		<td><?php echo $item['media']; ?></td>
	</tr>
	<?php endforeach; ?>
</table>
<br>


<form action="<?php echo $block->getSaveUrl(); ?>" method="post">
	<label for="name"> Nom:</label>
	<input type="text" name="name" id="name">
	<br><br>

	<label for="media">URL Media: </label>
	<input type="text" name="media" id="media">
	<br><br>
	<input type="submit" value="Add in BDD">
</form>